language: node_js
sudo: required
node_js:
  - 11

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - chmod +x start-server.sh

before_script:
  - yarn
  - './start-server.sh'

script:
  - yarn test

notifications:
  email:
    on_failure: change
